<?php
// init.php — Initialization and per-class management for lamectf2
session_start();
require __DIR__ . '/csrf.php';

$secret_dir = ($_SERVER['HOME'] ?? posix_getpwuid(posix_geteuid())['dir']) . '/.lamectf2';
if (!is_dir($secret_dir)) mkdir($secret_dir, 0700, true);

function h($s) { return htmlspecialchars($s, ENT_QUOTES); }

// ── Discover existing classes ────────────────────────────────────────────────
$known_classes = [];
foreach (glob($secret_dir . '/*_secret.php') ?: [] as $f) {
    if (preg_match('/\/([A-Za-z0-9_-]+)_secret\.php$/', $f, $m))
        $known_classes[] = $m[1];
}

// ── Determine mode: setup | landing | manage ─────────────────────────────────
$mode = 'landing';
$managing_course = '';
$error = '';
$upload_ok  = [];
$upload_err = [];

$_req_c   = trim($_GET['c']   ?? $_POST['c']   ?? '');
$_req_new = !empty($_GET['new']) || !empty($_POST['new']);

if (empty($known_classes) && !$_req_new) {
    $mode = 'setup'; // No classes yet — first-time setup
} elseif ($_req_new) {
    $mode = 'setup'; // Explicitly adding a new class
} elseif ($_req_c !== '' && in_array($_req_c, $known_classes, true)) {
    $mode = 'manage';
    $managing_course = $_req_c;
} elseif (!empty($known_classes) && $_req_c === '') {
    $mode = 'landing'; // Classes exist, none selected
}

// ── Variables used in HTML (defaults) ───────────────────────────────────────
$password_hash    = '';
$recaptcha_secret = '';
$recaptcha_sitekey = '';
$course_number    = '';
$initialized      = false;
$authed           = false;
$_init_prefix     = '';
$discussions_enabled = false;
$backup_config_file  = '';
$backup_enabled      = false;
$backup_email        = '';
$backup_agentmail_key = '';
$backup_zip_password  = '';

// Auto-fill reCAPTCHA and password from first existing class when adding a new one
$_setup_recap_site = '';
$_setup_recap_sec  = '';
$_existing_hash    = '';
if (!empty($known_classes)) {
    $_first_sec = $secret_dir . '/' . $known_classes[0] . '_secret.php';
    if (file_exists($_first_sec)) {
        $_sc = file_get_contents($_first_sec);
        preg_match('/\$recaptcha_sitekey\s*=\s*([\'"])(.*?)\1/', $_sc, $_rm);
        $_setup_recap_site = $_rm[2] ?? '';
        preg_match('/\$recaptcha_secret\s*=\s*([\'"])(.*?)\1/', $_sc, $_rm);
        $_setup_recap_sec  = $_rm[2] ?? '';
        // Extract password hash (bcrypt — single-quoted, may contain $ signs)
        preg_match('/\$password_hash\s*=\s*\'((?:[^\'\\\\]|\\\\.)*)\'/', $_sc, $_pm);
        if (empty($_pm[1])) preg_match('/\$password_hash\s*=\s*"((?:[^"\\\\]|\\\\.)*)"/', $_sc, $_pm);
        $_existing_hash = $_pm[1] ?? '';
    }
}

// ── SETUP mode: handle new class creation ────────────────────────────────────
if ($mode === 'setup' && $_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['submit_setup'])) {
    csrf_verify();
    $pass1      = $_POST['password']         ?? '';
    $pass2      = $_POST['password2']        ?? '';
    $recap_sec  = trim($_POST['recaptcha_secret']  ?? '');
    $recap_site = trim($_POST['recaptcha_sitekey'] ?? '');
    $course_num = preg_replace('/[^a-zA-Z0-9_\-]/', '', trim($_POST['course_number'] ?? ''));
    $course     = trim($_POST['course_name'] ?? '');

    // Fall back to existing reCAPTCHA keys and password hash when adding a second class
    if ($recap_sec  === '') $recap_sec  = $_setup_recap_sec;
    if ($recap_site === '') $recap_site = $_setup_recap_site;
    $_reuse_hash = ($_existing_hash !== ''); // skip password validation for 2nd+ class

    if ($course_num === '') {
        $error = 'Course number cannot be empty (e.g. CNIT_126_F26).';
    } elseif (in_array($course_num, $known_classes, true)) {
        $error = "Class $course_num already exists. Use a different course number or manage it below.";
    } elseif (!$_reuse_hash && $pass1 === '') {
        $error = 'Password cannot be empty.';
    } elseif (!$_reuse_hash && strlen($pass1) < 8) {
        $error = 'Password must be at least 8 characters.';
    } elseif (!$_reuse_hash && $pass1 !== $pass2) {
        $error = 'Passwords do not match.';
    } elseif ($recap_sec === '') {
        $error = 'reCAPTCHA secret key cannot be empty.';
    } elseif ($recap_site === '') {
        $error = 'reCAPTCHA site key cannot be empty.';
    } else {
        $hash = $_reuse_hash ? $_existing_hash : password_hash($pass1, PASSWORD_BCRYPT, ['cost' => 14]);
        $title  = $course_num . ($course !== '' ? ': ' . $course : '');
        $prefix = $course_num . '_';
        $php  = "<?php\n"
              . "// Generated by init.php — do not edit manually\n"
              . "// Lives in ~/.lamectf2/ outside the web root\n"
              . "\$password_hash      = " . var_export($hash, true) . ";\n"
              . "\$recaptcha_secret   = " . var_export($recap_sec, true) . ";\n"
              . "\$recaptcha_sitekey  = " . var_export($recap_site, true) . ";\n"
              . "\$course_number      = " . var_export($course_num, true) . ";\n"
              . "\$description        = " . var_export($title, true) . ";\n"
              . "\$logfile            = " . var_export($secret_dir . '/' . $prefix . 'scores.csv', true) . ";\n"
              . "\$xfile              = " . var_export($secret_dir . '/' . $prefix . 'scores_extra.csv', true) . ";\n"
              . "\$results_csv        = " . var_export($secret_dir . '/' . $prefix . 'quiz_results.csv', true) . ";\n"
              . "\$access_codes_csv   = " . var_export($secret_dir . '/' . $prefix . 'nick_access.csv', true) . ";\n"
              . "\$namefile           = " . var_export($secret_dir . '/' . $prefix . 'students.csv', true) . ";\n";
        $new_secret = $secret_dir . '/' . $course_num . '_secret.php';
        if (file_put_contents($new_secret, $php) === false) {
            $error = "Could not write $new_secret — check permissions.";
        } else {
            chmod($new_secret, 0600);
            // If section/CRN field not wanted, create no_section flag
            if (empty($_POST['ask_section'])) {
                $ns_flag = $secret_dir . '/' . $course_num . '_no_section';
                touch($ns_flag); chmod($ns_flag, 0600);
            }
            $_SESSION['init_authed_' . $course_num] = true;
            session_regenerate_id(true);
            header('Location: init.php?c=' . urlencode($course_num));
            exit;
        }
    }
}

// ── MANAGE mode: load class, handle all POSTs ────────────────────────────────
if ($mode === 'manage') {
    $secret_file = $secret_dir . '/' . $managing_course . '_secret.php';
    if (file_exists($secret_file)) {
        include $secret_file;
        $initialized = !empty($password_hash);
    }
    $_init_prefix = !empty($course_number) ? $course_number . '_' : '';
    $authed       = !empty($_SESSION['init_authed_' . $managing_course]);

    // Logout
    if (isset($_GET['logout'])) {
        $_SESSION['init_authed_' . $managing_course] = false;
        header('Location: init.php?c=' . urlencode($managing_course));
        exit;
    }

    // Login
    if ($initialized && !$authed && $_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['submit_login'])) {
        csrf_verify();
        if (password_verify($_POST['password'] ?? '', $password_hash)) {
            $_SESSION['init_authed_' . $managing_course] = true;
            session_regenerate_id(true);
            $authed = true;
        } else {
            $error = 'Wrong password.';
        }
    }

    // Load backup settings (global — shared across all classes)
    $backup_config_file   = $secret_dir . '/backup.php';
    $agentmail_key        = '';
    if (file_exists($backup_config_file)) @include $backup_config_file;
    if (empty($backup_agentmail_key)) $backup_agentmail_key = $agentmail_key;

    // Discussions state
    $discussions_enabled = file_exists($secret_dir . '/' . $_init_prefix . 'discussions_enabled');
    // Section/CRN field state (on by default — flag file disables it)
    $section_enabled = !file_exists($secret_dir . '/' . $_init_prefix . 'no_section');

    // CTF answers are shared across all classes
    $ctf_answers_exists = file_exists($secret_dir . '/CTF_answers.php');
    // Per-class challenge list
    $class_chals_file   = $secret_dir . '/' . $_init_prefix . 'CTF_answers.php';
    $class_chals_exists = file_exists($class_chals_file);

    if ($authed && $_SERVER['REQUEST_METHOD'] === 'POST') {
        csrf_verify();

        if (isset($_POST['save_backup'])) {
            $bk_on  = !empty($_POST['backup_enabled']);
            $bk_em  = trim($_POST['backup_email']         ?? '');
            $bk_key = trim($_POST['backup_agentmail_key'] ?? '');
            $bk_pw  = trim($_POST['backup_zip_password']  ?? '');
            $php = "<?php\n"
                 . "\$backup_enabled       = " . ($bk_on ? 'true' : 'false') . ";\n"
                 . "\$backup_email         = " . var_export($bk_em,  true) . ";\n"
                 . "\$backup_agentmail_key = " . var_export($bk_key, true) . ";\n"
                 . "\$backup_zip_password  = " . var_export($bk_pw,  true) . ";\n";
            if (file_put_contents($backup_config_file, $php) !== false) {
                chmod($backup_config_file, 0600);
                $backup_enabled = $bk_on; $backup_email = $bk_em;
                $backup_agentmail_key = $bk_key; $backup_zip_password = $bk_pw;
                $upload_ok[] = 'Backup settings saved.';
            } else {
                $upload_err[] = 'Could not write backup config.';
            }
        }

        if (isset($_POST['submit_files'])) {
            if (!empty($_FILES['quiz_files']['name'][0])) {
                foreach ($_FILES['quiz_files']['name'] as $i => $name) {
                    if ($_FILES['quiz_files']['error'][$i] !== UPLOAD_ERR_OK || $name === '') continue;
                    $safe = preg_replace('/[^a-zA-Z0-9._\-]/', '_', basename($name));
                    if (!preg_match('/\.(txt|php)$/i', $safe)) $safe .= '.txt';
                    $dest = $secret_dir . '/' . $safe;
                    if (move_uploaded_file($_FILES['quiz_files']['tmp_name'][$i], $dest)) {
                        chmod($dest, 0600); $upload_ok[] = "Quiz file saved: $safe";
                    } else { $upload_err[] = "Failed to save: $safe"; }
                }
            }
            if (!empty($_FILES['ctf_answers']['name']) && $_FILES['ctf_answers']['error'] === UPLOAD_ERR_OK) {
                $dest = $secret_dir . '/CTF_answers.php';
                if (move_uploaded_file($_FILES['ctf_answers']['tmp_name'], $dest)) {
                    chmod($dest, 0600);
                    $ctf_answers_exists = true;
                    $upload_ok[] = 'CTF answers saved (shared across all classes).';
                } else { $upload_err[] = 'Failed to save CTF answers.'; }
            }
        }

        if (isset($_POST['use_quiz_example'])) {
            $src = __DIR__ . '/quiz_example.txt'; $dest = $secret_dir . '/quiz_example.txt';
            if (file_exists($src) && copy($src, $dest)) {
                chmod($dest, 0600); $upload_ok[] = 'Example quiz file installed.';
            } else { $upload_err[] = 'Could not copy quiz_example.txt'; }
        }
        if (isset($_POST['use_ctf_example'])) {
            $src  = __DIR__ . '/CTF_answers_example.php';
            $dest = $secret_dir . '/CTF_answers.php';
            if (file_exists($src) && copy($src, $dest)) {
                chmod($dest, 0600); $ctf_answers_exists = true; $upload_ok[] = 'Example CTF answers installed (shared across all classes).';
            } else { $upload_err[] = 'Could not copy CTF_answers_example.php'; }
        }

        if (isset($_POST['submit_class_chals']) && !empty($_FILES['class_chals_file']['name'])) {
            $uf = $_FILES['class_chals_file'];
            if ($uf['error'] !== UPLOAD_ERR_OK) {
                $upload_err[] = 'Upload error: ' . $uf['error'];
            } elseif (move_uploaded_file($uf['tmp_name'], $class_chals_file)) {
                chmod($class_chals_file, 0600);
                $class_chals_exists = true;
                $upload_ok[] = 'Challenge list saved for ' . h($managing_course) . '.';
            } else {
                $upload_err[] = 'Could not save challenge list.';
            }
        }

        if (isset($_POST['toggle_discussions'])) {
            $flag = $secret_dir . '/' . $_init_prefix . 'discussions_enabled';
            if ($discussions_enabled) {
                unlink($flag); $discussions_enabled = false; $upload_ok[] = 'Discussions disabled.';
            } else {
                touch($flag); chmod($flag, 0600); $discussions_enabled = true; $upload_ok[] = 'Discussions enabled.';
            }
        }

        if (isset($_POST['toggle_section'])) {
            $flag = $secret_dir . '/' . $_init_prefix . 'no_section';
            if ($section_enabled) {
                touch($flag); chmod($flag, 0600); $section_enabled = false; $upload_ok[] = 'Section/CRN field disabled.';
            } else {
                unlink($flag); $section_enabled = true; $upload_ok[] = 'Section/CRN field enabled.';
            }
        }

        if (isset($_POST['upload_students']) && !empty($_FILES['student_file']['name'])) {
            $uf = $_FILES['student_file'];
            if ($uf['error'] !== UPLOAD_ERR_OK) {
                $upload_err[] = 'Upload error: ' . $uf['error'];
            } else {
                // Load existing nicks to detect duplicates
                $existing_nicks = [];
                if (file_exists($namefile)) {
                    $efh = fopen($namefile, 'r');
                    while ($efh && ($er = fgetcsv($efh)) !== false)
                        if (!empty($er[0])) $existing_nicks[strtolower(trim($er[0]))] = true;
                    if ($efh) fclose($efh);
                }
                // Load existing access-code nicks
                $existing_code_nicks = [];
                if (file_exists($access_codes_csv)) {
                    $afh = fopen($access_codes_csv, 'r');
                    fgetcsv($afh); // skip header
                    while ($afh && ($ar = fgetcsv($afh)) !== false)
                        if (!empty($ar[0])) $existing_code_nicks[strtolower(trim($ar[0]))] = true;
                    if ($afh) fclose($afh);
                }
                $nfh = fopen($namefile, 'a');
                $need_header = !file_exists($access_codes_csv) || filesize($access_codes_csv) === 0;
                $cfh = fopen($access_codes_csv, 'a');
                if ($need_header) fputcsv($cfh, ['Nickname', 'Access Code']);
                $added = 0; $skipped = 0; $first_row = true;
                $tmpfh = fopen($uf['tmp_name'], 'r');
                while ($tmpfh && ($row = fgetcsv($tmpfh)) !== false) {
                    if (count($row) < 2) continue;
                    $nick = trim($row[0]);
                    // Skip header rows
                    if ($first_row && strtolower($nick) === 'nickname') { $first_row = false; continue; }
                    $first_row = false;
                    if ($nick === '') continue;
                    $lnick = strtolower($nick);
                    if (isset($existing_nicks[$lnick])) { $skipped++; continue; }
                    // Columns: nick, last_name, first_name, student_id, section, access_code
                    // Also accept: nick, "Last, First", student_id, section, access_code (5-col)
                    if (count($row) >= 6) {
                        $full_name   = trim($row[1]) . ', ' . trim($row[2]);
                        $student_id  = trim($row[3]);
                        $section     = trim($row[4]);
                        $access_code = trim($row[5]);
                    } elseif (count($row) >= 5) {
                        // 5-col: nick, "Last, First", id, section, access_code
                        $full_name   = trim($row[1]);
                        $student_id  = trim($row[2]);
                        $section     = trim($row[3]);
                        $access_code = trim($row[4]);
                    } else {
                        // 2-col minimum: nick, access_code only
                        $full_name = $nick; $student_id = ''; $section = ''; $access_code = trim($row[1]);
                    }
                    fputcsv($nfh, [$nick, $full_name, $student_id, $section]);
                    if (!isset($existing_code_nicks[$lnick]))
                        fputcsv($cfh, [$nick, $access_code]);
                    $existing_nicks[$lnick] = true;
                    $added++;
                }
                if ($tmpfh) fclose($tmpfh);
                fclose($nfh); fclose($cfh);
                if ($added > 0)   $upload_ok[]  = "Added $added student(s).";
                if ($skipped > 0) $upload_ok[]  = "Skipped $skipped duplicate nickname(s).";
                if ($added === 0 && $skipped === 0) $upload_err[] = 'No valid rows found in file.';
            }
        }
    }
}
?><!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>lamectf2 Setup</title>
<style>
  body  { font-family: Arial, sans-serif; max-width: 720px; margin: 50px auto; padding: 0 20px; }
  h1   { font-size: 1.5em; }
  h2   { font-size: 1.15em; margin: 0 0 8px; }
  .box { background: #f8f8f8; border: 1px solid #ccc; padding: 18px 20px; border-radius: 6px; margin: 22px 0; }
  pre  { background: #222; color: #eee; padding: 14px; border-radius: 5px; overflow-x: auto; font-size: 0.85em; line-height: 1.4; margin: 8px 0 14px; }
  label { display: block; margin: 10px 0 4px; font-weight: bold; }
  input[type=password], input[type=text] { width: 100%; padding: 8px; font-size: 1em; margin: 4px 0; box-sizing: border-box; }
  input[type=file]   { font-size: 1em; }
  input[type=submit] { margin-top: 14px; padding: 10px 26px; font-size: 1.05em; cursor: pointer; }
  .ok   { color: #040; background: #dfd; border: 1px solid #4a4; padding: 8px 12px; border-radius: 4px; margin: 5px 0; }
  .err  { color: #c00; background: #fdd; border: 1px solid #c00; padding: 8px 12px; border-radius: 4px; margin: 5px 0; }
  .note { background: #fffbe6; border: 1px solid #cc9; padding: 10px 14px; border-radius: 4px; margin: 12px 0; }
  code  { background: #f0f0f0; padding: 2px 5px; border-radius: 3px; }
  small { color: #555; }
  nav   { text-align: right; font-size: 0.9em; margin-bottom: 10px; }
  .class-list { list-style: none; padding: 0; margin: 16px 0; }
  .class-list li { margin: 8px 0; }
  .class-list a { display:inline-block; padding: 10px 16px; background: #f0f4ff; border: 1px solid #99b; border-radius: 5px; text-decoration: none; color: #222; }
  .class-list a:hover { background: #dde8ff; }
</style>
<script>
function togglePw(checkbox, formId) {
  var inputs = document.getElementById(formId).querySelectorAll('input[type=password],input.pw-field');
  inputs.forEach(function(el) { el.type = checkbox.checked ? 'text' : 'password'; });
}
</script>
</head>
<body>

<h1>lamectf2 Setup</h1>

<?php if ($error): ?>
<div class="err"><?php echo h($error); ?></div>
<?php endif; ?>

<?php

// ═══════════════════════════════════════════════════════════════════════════
// LANDING MODE — list classes, offer to add new
// ═══════════════════════════════════════════════════════════════════════════
if ($mode === 'landing'):

$_landing_classes = [];
foreach ($known_classes as $_lc) {
    $_sf = $secret_dir . '/' . $_lc . '_secret.php';
    $_desc = $_lc;
    if (file_exists($_sf)) {
        preg_match('/\$description\s*=\s*([\'"])(.*?)\1/', file_get_contents($_sf), $_dm);
        if (!empty($_dm[2])) $_desc = $_dm[2];
    }
    $_landing_classes[] = ['course' => $_lc, 'desc' => $_desc];
}
?>
<p>Configured classes:</p>
<ul class="class-list">
<?php foreach ($_landing_classes as $_cl): ?>
  <li>
    <a href="init.php?c=<?php echo urlencode($_cl['course']); ?>">
      <?php echo h($_cl['desc']); ?>
      <small>(<?php echo h($_cl['course']); ?>)</small>
    </a>
    &nbsp;
    <a href="index.php?c=<?php echo urlencode($_cl['course']); ?>" style="font-size:0.9em;color:#555">[Student page &rarr;]</a>
  </li>
<?php endforeach; ?>
</ul>
<p><a href="init.php?new=1"><strong>+ Add another class</strong></a></p>

<?php

// ═══════════════════════════════════════════════════════════════════════════
// SETUP MODE — create a new class
// ═══════════════════════════════════════════════════════════════════════════
elseif ($mode === 'setup'):

$_is_first = empty($known_classes);
?>
<p><?php echo $_is_first ? 'No classes configured yet. Create your first class to get started.' : 'Add a new class to this installation.'; ?></p>
<?php if (!$_is_first): ?><p><a href="init.php">&larr; Back to class list</a></p><?php endif; ?>
<p><small>Secrets will be stored in <code><?php echo h($secret_dir); ?></code> (mode 700/600).</small></p>
<form method="post" id="form-setup">
  <?php echo csrf_field(); ?>
  <input type="hidden" name="new" value="1">
  <label>Course number: <small>(used in filenames — letters, numbers, underscores, e.g. CNIT_126_F26)</small></label>
  <input type="text" name="course_number" placeholder="CNIT_126_F26" pattern="[a-zA-Z0-9_\-]+" required>
  <label>Course name: <small>(shown on scoreboard — e.g. "Networking Fundamentals, Spring 2026")</small></label>
  <input type="text" name="course_name" placeholder="Introduction to Networking, Spring 2026">
  <?php if ($_existing_hash !== ''): ?>
  <p class="note"><small>Admin password reused from existing class (<code><?php echo h($known_classes[0]); ?></code>). All classes share one password.</small></p>
  <?php else: ?>
  <label>Admin password: <small>(8+ characters — shared by all classes you add later)</small></label>
  <input type="password" name="password" autofocus>
  <label>Confirm password:</label>
  <input type="password" name="password2">
  <div style="margin:8px 0"><input type="checkbox" id="show-pw-setup" onchange="togglePw(this,'form-setup')"> <label for="show-pw-setup" style="display:inline;font-weight:normal">Show passwords</label></div>
  <?php endif; ?>
  <?php if (!$_is_first && $_setup_recap_site !== ''): ?>
  <input type="hidden" name="recaptcha_sitekey" value="<?php echo h($_setup_recap_site); ?>">
  <input type="hidden" name="recaptcha_secret" value="<?php echo h($_setup_recap_sec); ?>">
  <p class="note"><small>reCAPTCHA keys reused from existing class (<code><?php echo h($known_classes[0]); ?></code>).</small></p>
  <?php else: ?>
  <label>reCAPTCHA site key: <small>(public key — get both keys from <a href="https://www.google.com/recaptcha/admin/create" target="_blank">Google reCAPTCHA Console</a>)</small></label>
  <input type="text" name="recaptcha_sitekey" placeholder="6Lx...">
  <label>reCAPTCHA secret key: <small>(private key, for server-side verification)</small></label>
  <input type="text" name="recaptcha_secret" placeholder="6Lx...">
  <?php endif; ?>
  <div style="margin:8px 0"><input type="checkbox" name="ask_section" id="ask_section" value="1" checked> <label for="ask_section" style="display:inline;font-weight:normal">Ask for section/CRN number during student registration</label></div>
  <input type="submit" name="submit_setup" value="Create Class &#8594;">
</form>

<?php

// ═══════════════════════════════════════════════════════════════════════════
// MANAGE MODE — admin a specific class
// ═══════════════════════════════════════════════════════════════════════════
elseif ($mode === 'manage'):
?>

<p style="font-size:0.9em"><a href="init.php">&larr; All classes</a>
  &nbsp;|&nbsp; Managing: <strong><?php echo h($course_number ?: $managing_course); ?></strong>
  <?php if ($authed): ?>&nbsp;|&nbsp; <a href="init.php?c=<?php echo urlencode($managing_course); ?>&logout=1">Log out</a><?php endif; ?>
</p>

<?php if (!$authed): ?>
<p>Enter the admin password to manage <strong><?php echo h($course_number ?: $managing_course); ?></strong>.</p>
<div class="note"><small>Password lost? Delete <code><?php echo h($secret_dir . '/' . $managing_course . '_secret.php'); ?></code> to reset.</small></div>
<form method="post" id="form-login" style="max-width:380px" action="init.php?c=<?php echo urlencode($managing_course); ?>">
  <?php echo csrf_field(); ?>
  <input type="hidden" name="c" value="<?php echo h($managing_course); ?>">
  <label>Admin password:</label>
  <input type="password" name="password" autofocus>
  <div style="margin:8px 0"><input type="checkbox" id="show-pw-login" onchange="togglePw(this,'form-login')"> <label for="show-pw-login" style="display:inline;font-weight:normal">Show password</label></div>
  <input type="submit" name="submit_login" value="Log In">
</form>

<?php else: ?>

<?php foreach ($upload_ok  as $m): ?><div class="ok">&#10003; <?php echo h($m); ?></div><?php endforeach; ?>
<?php foreach ($upload_err as $e): ?><div class="err">&#10007; <?php echo h($e); ?></div><?php endforeach; ?>

<p>Files are stored in <code><?php echo h($secret_dir); ?></code> — outside the web root.</p>

<?php
// Helper: a form for this class
$_c_hidden = '<input type="hidden" name="c" value="' . h($managing_course) . '">';
$_c_action = 'action="init.php?c=' . urlencode($managing_course) . '"';
function _c_action_s($c, $s) { return 'action="init.php?c=' . urlencode($c) . '&scroll=' . $s . '"'; }
?>

<div class="box" id="section-students">
  <h2>Students</h2>
  <?php
  $student_count = 0;
  if (file_exists($namefile)) {
      $sfh = fopen($namefile, 'r');
      while ($sfh && fgetcsv($sfh) !== false) $student_count++;
      if ($sfh) fclose($sfh);
  }
  ?>
  <p><?php echo $student_count; ?> student(s) registered.
     Students can also self-register at <a href="register_form.php?c=<?php echo urlencode($managing_course); ?>">register_form.php</a>.</p>
  <p>To bulk-load students, upload a CSV file. <strong>Duplicate nicknames are skipped.</strong></p>
  <p><strong>Required format</strong> — one student per line, no header required:</p>
  <pre style="font-size:0.85em">nickname, last_name, first_name, student_id, section, access_code

Examples:
jsmith, Smith, Jane, 1234, 71234, forest_river
mbrown, Brown, Mike, 5678, 71234, silver_thunder</pre>
  <p style="margin:4px 0 8px"><small>
    <strong>nickname</strong> — short ID shown on scoreboard &nbsp;|&nbsp;
    <strong>last_name / first_name</strong> — stored as "Last, First" &nbsp;|&nbsp;
    <strong>student_id</strong> — last 4 digits &nbsp;|&nbsp;
    <strong>section</strong> — CRN or section number &nbsp;|&nbsp;
    <strong>access_code</strong> — code student uses to log in and take quizzes
  </small></p>
  <p><small>Also accepts 5-column format (nick, "Last, First", id, section, access_code) or 2-column (nick, access_code).</small></p>
  <form method="post" enctype="multipart/form-data" <?php echo _c_action_s($managing_course,'section-students'); ?>>
    <?php echo csrf_field(); echo $_c_hidden; ?>
    <input type="file" name="student_file" accept=".csv,.txt" required>
    <input type="submit" name="upload_students" value="Upload Students">
  </form>
</div>

<div class="box" id="section-quiz">
  <h2>Quiz Files <small>(.txt)</small></h2>
  <p>The <strong>first answer listed under each question is correct</strong>; the rest are distractors shown in random order.</p>
  <pre>Title: Example Quiz 8 pts
Select: 2
Points per question: 4
Number of Attempts: 2

1 Which of the following is a compiled language?

C
Python
JavaScript
Ruby

2 What does HTML stand for?

HyperText Markup Language
HighLevel Text Manipulation Language
HyperText Management Language
HyperLink and Text Markup Language</pre>
  <p><small><code>Select: 2</code> — pick 2 questions at random per attempt &nbsp;|&nbsp;
     <code>Number of Attempts: 2</code> — each student may submit twice</small></p>
  <form method="post" enctype="multipart/form-data" <?php echo $_c_action; ?>>
    <?php echo csrf_field(); echo $_c_hidden; ?>
    <label for="quiz_files">Select quiz file(s):</label>
    <input type="file" name="quiz_files[]" id="quiz_files" multiple accept=".txt">
    <input type="submit" name="submit_files" value="Upload Quiz Files">
  </form>
  <form method="post" style="margin-top:8px" <?php echo _c_action_s($managing_course,'section-quiz'); ?>>
    <?php echo csrf_field(); echo $_c_hidden; ?>
    <input type="submit" name="use_quiz_example" value="Use Example Quiz File">
    <small> — installs the built-in <code>quiz_example.txt</code> as a starting point</small>
  </form>
</div>

<!-- ── Master Answers File (shared across all classes) ── -->
<div class="box" id="section-ctf">
  <h2>Master Answers File <small>(all classes)</small></h2>
  <?php if ($ctf_answers_exists): ?>
  <p><strong style="color:green">&#10003; CTF_answers.php is installed</strong> — shared across all classes.</p>
  <?php else: ?>
  <p>Not yet installed.</p>
  <?php endif; ?>
  <p>Contains correct flag values and point scores for <strong>every challenge across all classes</strong>.
     Challenge IDs must start and end with underscore.</p>
  <pre style="font-size:0.82em">&lt;?php
// Master answers — all challenges for all classes
// [ "Challenge_ID",  "correct_flag",   points ]
$correct_answers = array(
    ["_Web 1_",    "FLAG{hello}",   10],
    ["_Web 2_",    "FLAG{world}",   20],
    ["_Crypto 1_", "FLAG{secret}",  15],
    ["_Forensics 1_", "FLAG{found}", 25],
);
?&gt;</pre>
  <form method="post" enctype="multipart/form-data" <?php echo _c_action_s($managing_course,'section-ctf'); ?>>
    <?php echo csrf_field(); echo $_c_hidden; ?>
    <label for="ctf_answers"><?php echo $ctf_answers_exists ? 'Replace' : 'Upload'; ?> master answers file (.php):</label>
    <input type="file" name="ctf_answers" id="ctf_answers" accept=".php,.txt">
    <input type="submit" name="submit_files" value="<?php echo $ctf_answers_exists ? 'Upload New' : 'Upload'; ?> Master Answers">
  </form>
  <?php if (!$ctf_answers_exists): ?>
  <form method="post" style="margin-top:8px" <?php echo _c_action_s($managing_course,'section-ctf'); ?>>
    <?php echo csrf_field(); echo $_c_hidden; ?>
    <input type="submit" name="use_ctf_example" value="Use Example Answers">
    <small> — installs the built-in example</small>
  </form>
  <?php endif; ?>
</div>

<!-- ── Per-class Challenge List ── -->
<div class="box" id="section-class-chals">
  <h2>Challenge List <small>(this class only)</small></h2>
  <?php if ($class_chals_exists): ?>
  <p><strong style="color:green">&#10003; Challenge list installed</strong> for <strong><?php echo h($managing_course); ?></strong>.</p>
  <?php else: ?>
  <p>No challenge list for <strong><?php echo h($managing_course); ?></strong> yet — students will see the default list.</p>
  <?php endif; ?>
  <p>Defines which challenges appear for <strong>this class only</strong> using IDs from the master answers file.
     Each class has its own file: <code><?php echo h($_init_prefix); ?>CTF_answers.php</code></p>
  <pre style="font-size:0.82em">&lt;?php
// Challenge list for <?php echo h($managing_course); ?> — IDs must exist in master answers file
// LABEL_Name  — series label shown in the Series dropdown
// "_Chal_"    — a submittable challenge (must match a master answers ID)
// "BREAK"     — visual separator between series
$poss_chals = [
    "LABEL_Web",     "_Web 1_",     "_Web 2_",     "BREAK",
    "LABEL_Crypto",  "_Crypto 1_",
];
?&gt;</pre>
  <p><small>
    <strong>LABEL_</strong> — text after it becomes the Series dropdown name &nbsp;|&nbsp;
    <strong>BREAK</strong> — challenges after it show only when their series is selected
  </small></p>
  <form method="post" enctype="multipart/form-data" <?php echo _c_action_s($managing_course,'section-class-chals'); ?>>
    <?php echo csrf_field(); echo $_c_hidden; ?>
    <label for="class_chals_file"><?php echo $class_chals_exists ? 'Replace' : 'Upload'; ?> challenge list (.php):</label>
    <input type="file" name="class_chals_file" id="class_chals_file" accept=".php,.txt">
    <input type="submit" name="submit_class_chals" value="<?php echo $class_chals_exists ? 'Replace' : 'Upload'; ?> Challenge List">
  </form>
</div>

<div class="box" id="section-discussions">
  <h2>Discussions</h2>
  <p>Enable manually-entered participation scores for up to 12 discussions per student.</p>
  <?php if ($discussions_enabled): ?>
  <p><strong style="color:green">&#10003; Discussions: ON</strong></p>
  <form method="post" <?php echo _c_action_s($managing_course,'section-discussions'); ?>>
    <?php echo csrf_field(); echo $_c_hidden; ?>
    <input type="submit" name="toggle_discussions" value="Disable Discussions">
  </form>
  <?php else: ?>
  <p><strong style="color:#999">Discussions: OFF</strong></p>
  <form method="post" <?php echo _c_action_s($managing_course,'section-discussions'); ?>>
    <?php echo csrf_field(); echo $_c_hidden; ?>
    <input type="submit" name="toggle_discussions" value="Enable Discussions">
  </form>
  <?php endif; ?>
</div>

<div class="box" id="section-section">
  <h2>Section/CRN Field</h2>
  <p>Show or hide the Section/CRN number field on the student registration form.</p>
  <?php if ($section_enabled): ?>
  <p><strong style="color:green">&#10003; Section field: ON</strong></p>
  <form method="post" <?php echo _c_action_s($managing_course,'section-section'); ?>>
    <?php echo csrf_field(); echo $_c_hidden; ?>
    <input type="submit" name="toggle_section" value="Disable Section Field">
  </form>
  <?php else: ?>
  <p><strong style="color:#999">Section field: OFF</strong></p>
  <form method="post" <?php echo _c_action_s($managing_course,'section-section'); ?>>
    <?php echo csrf_field(); echo $_c_hidden; ?>
    <input type="submit" name="toggle_section" value="Enable Section Field">
  </form>
  <?php endif; ?>
</div>

<div class="box" id="section-backup">
  <h2>Score Backup</h2>
  <?php if ($backup_enabled && !empty($backup_email)): ?>
  <p><strong style="color:green">&#10003; Backup enabled</strong> — sending to <code><?php echo h($backup_email); ?></code></p>
  <p style="margin-top:10px">To set up nightly automated backups, SSH into the server as the same
     user who uploaded the lamectf folder, <strong>cd to the lamectf directory</strong>, then run:</p>
  <?php
  $cron_install_cmd = '(crontab -l 2>/dev/null; echo "0 0 * * * php $(realpath backup_cron.php) >> $HOME/.lamectf2/backup.log 2>&1") | crontab -';
  ?>
  <div style="position:relative;margin:10px 0">
    <pre id="cron-install-cmd" style="font-size:0.82em;background:#1e1e1e;color:#d4d4d4;padding:12px 90px 12px 14px;border-radius:6px;overflow-x:auto;white-space:pre-wrap;word-break:break-all"><?php echo h($cron_install_cmd); ?></pre>
    <button type="button" id="cron-copy-btn"
      onclick="(function(){var t=document.getElementById('cron-install-cmd').innerText.trim();if(navigator.clipboard){navigator.clipboard.writeText(t).then(function(){var b=document.getElementById('cron-copy-btn');b.textContent='Copied!';setTimeout(function(){b.textContent='Copy';},2000);});}else{var ta=document.createElement('textarea');ta.value=t;document.body.appendChild(ta);ta.select();document.execCommand('copy');document.body.removeChild(ta);var b=document.getElementById('cron-copy-btn');b.textContent='Copied!';setTimeout(function(){b.textContent='Copy';},2000);}})();"
      style="position:absolute;top:8px;right:8px;padding:5px 12px;font-size:0.82em;cursor:pointer;background:#444;color:#fff;border:none;border-radius:4px">Copy</button>
  </div>
  <p style="font-size:0.9em;color:#555">Runs at midnight daily. Logs to <code>~/.lamectf2/backup.log</code>.</p>
  <details style="margin-top:10px"><summary style="cursor:pointer;color:#555;font-size:0.9em">Change backup settings&hellip;</summary>
  <div style="margin-top:10px">
  <form method="post" <?php echo _c_action_s($managing_course,'section-backup'); ?>>
    <?php echo csrf_field(); echo $_c_hidden; ?>
    <label style="font-weight:normal;margin:6px 0">
      <input type="checkbox" name="backup_enabled" value="1" <?php if ($backup_enabled) echo 'checked'; ?>>
      &nbsp;<strong>Enable score backup</strong>
    </label>
    <label>AgentMail API key:</label>
    <input type="text" name="backup_agentmail_key" value="<?php echo h($backup_agentmail_key); ?>" placeholder="am_...">
    <label>Destination email:</label>
    <input type="text" name="backup_email" value="<?php echo h($backup_email); ?>" placeholder="teacher@example.com">
    <label>Zip password:</label>
    <input type="text" name="backup_zip_password" value="<?php echo h($backup_zip_password); ?>" placeholder="choose a strong password">
    <input type="submit" name="save_backup" value="Save Backup Settings" style="margin-top:10px">
  </form>
  </div></details>
  <?php else: ?>
  <p>When enabled, score files are emailed as a password-protected zip via AgentMail.</p>
  <form method="post" <?php echo _c_action_s($managing_course,'section-backup'); ?>>
    <?php echo csrf_field(); echo $_c_hidden; ?>
    <label style="font-weight:normal;margin:6px 0">
      <input type="checkbox" name="backup_enabled" value="1" id="bk-chk"
        onchange="document.getElementById('bk-fields').style.display=this.checked?'block':'none'">
      &nbsp;<strong>Enable score backup</strong>
    </label>
    <div id="bk-fields" style="display:none;margin-top:10px">
      <label>AgentMail API key: <small>(<a href="https://agentmail.to" target="_blank">agentmail.to</a>)</small></label>
      <input type="text" name="backup_agentmail_key" value="" placeholder="am_...">
      <label>Destination email:</label>
      <input type="text" name="backup_email" value="" placeholder="teacher@example.com">
      <label>Zip password:</label>
      <input type="text" name="backup_zip_password" value="" placeholder="choose a strong password">
    </div>
    <input type="submit" name="save_backup" value="Save Backup Settings" style="margin-top:12px">
  </form>
  <?php endif; ?>
</div>

<div class="box">
  <h2>Ready to go?</h2>
  <?php
  $_proto       = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
  $_base_url    = $_proto . '://' . $_SERVER['HTTP_HOST'] . rtrim(dirname($_SERVER['SCRIPT_NAME']), '/\\') . '/';
  $_student_url = $_base_url . 'login.php?c=' . urlencode($managing_course);
  ?>
  <p><strong>Student URL</strong> — share this link with your students:</p>
  <div style="position:relative;margin:6px 0 14px">
    <code id="student-url" style="display:block;background:#f0f4ff;border:1px solid #99b;padding:10px 90px 10px 12px;border-radius:4px;font-size:1em;word-break:break-all"><?php echo h($_student_url); ?></code>
    <button type="button"
      onclick="(function(){var t=document.getElementById('student-url').innerText.trim();if(navigator.clipboard){navigator.clipboard.writeText(t).then(function(){var b=document.getElementById('url-copy-btn');b.textContent='Copied!';setTimeout(function(){b.textContent='Copy';},2000);});}else{var ta=document.createElement('textarea');ta.value=t;document.body.appendChild(ta);ta.select();document.execCommand('copy');document.body.removeChild(ta);var b=document.getElementById('url-copy-btn');b.textContent='Copied!';setTimeout(function(){b.textContent='Copy';},2000);}})();"
      id="url-copy-btn"
      style="position:absolute;top:8px;right:8px;padding:5px 12px;font-size:0.85em;cursor:pointer;background:#0066ff;color:#fff;border:none;border-radius:4px">Copy</button>
  </div>
  <p>
    <a href="index.php?c=<?php echo urlencode($managing_course); ?>"><big><b>Go to flag submission &rarr;</b></big></a>
    &nbsp; &nbsp;
    <a href="admin.php?c=<?php echo urlencode($managing_course); ?>">Admin panel</a>
  </p>
</div>

<?php endif; // authed ?>
<?php endif; // mode === 'manage' ?>

<script>
(function(){
  var p = new URLSearchParams(window.location.search);
  var s = p.get('scroll');
  if (s) { var el = document.getElementById(s); if (el) el.scrollIntoView({behavior:'smooth',block:'start'}); }
})();
</script>
</body>
</html>
