<?php
// Generated by init.php — do not edit manually
// This file lives in ~/.lamectf2/ outside the web root
$password_hash     = '';
$recaptcha_secret  = '';
$recaptcha_sitekey = '';
$course_number     = '';
$description       = '';
$logfile           = '';
$xfile             = '';
$results_csv       = '';
$access_codes_csv  = '';
$namefile          = '';
